services:
  ftpslurper:
    container_name: "ftpslurper"
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - 8080:8080

  postgres:
    container_name: "ftpslurper-postgres"
    image: postgres:15.2
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ftpslurper-postgres:/var/lib/postgresql/data

volumes:
  ftpslurper-postgres:
